name: Update StackOverflow activity
on:
  schedule: 
    # Runs every day, at 00:00 UTC
    - cron: '0 0 * * *' 
  workflow_dispatch:
permissions:
    contents: write

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest StackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/9586535"

          
